url: https://lequieu.github.io
baseurl: /1cpn-model/
downloadurl: https://github.com/lequieu/1cpn-model
docurl: docs/

# Site settings
title: 1CPN Model
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."



# Team names, titles and social links
people:
- name: Joshua Lequieu
  pic: lequieu
  position: Former Ph.D. @ U Chicago, currently UCSB

- name: Andres Cordoba
  pic: acordoba
  position: Former Post-Doc @ U Chicago, currently Universidad de Concepci√≥n

- name: Joshua Moller
  pic: moller
  position: Graduate Student @ U Chicago

- name: Juan de Pablo
  pic: dePablo
  position: Professor @ U Chicago



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# force include documentation
include: 
    - docs
keep_files:
    - docs/_static




